PROJECT_ID: "sandbox-egl1hjn"
DESTINATION_BLOB_DIR: "test"
BUCKET_NAME: "football-match-data"
JOBS:
    -   ID: "2122_E0"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/2122/E0.csv"
        OUTPUT_FILE_PREFIX: "2122_E0"
    -   ID: "2021_E0"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/2021/E0.csv"
        OUTPUT_FILE_PREFIX: "2021_E0"
    -   ID: "1920_E0"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/1920/E0.csv"
        OUTPUT_FILE_PREFIX: "1920_E0"
    -   ID: "1819_E0"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/1819/E0.csv"
        OUTPUT_FILE_PREFIX: "1819_E0"
    -   ID: "1718_E0"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/1718/E0.csv"
        OUTPUT_FILE_PREFIX: "1718_E0"
    -   ID: "2122_E1"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/2122/E1.csv"
        OUTPUT_FILE_PREFIX: "2122_E1"
    -   ID: "2021_E1"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/2021/E1.csv"
        OUTPUT_FILE_PREFIX: "2021_E1"
    -   ID: "1920_E1"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/1920/E1.csv"
        OUTPUT_FILE_PREFIX: "1920_E1"
    -   ID: "1819_E1"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/1819/E1.csv"
        OUTPUT_FILE_PREFIX: "1819_E1"
    -   ID: "1718_E1"
        SOURCE_URL: "https://www.football-data.co.uk/mmz4281/1718/E1.csv"
        OUTPUT_FILE_PREFIX: "1718_E1"
